name: Generate Snake Animation

on:
 schedule:
   - cron: "0 0 * * *"  # Executa todos os dias à meia-noite UTC

   workflow_dispatch:  # Permite execução manual

   jobs:
     generate:
       runs-on: ubuntu-lastest
       steps:
       - name: Checkout do repositório
         uses: actions/checkout@v3

       - name: Gerar a animação da cobrinha
         uses: Platane/snk@v3
         with:
           github_user_name:  $ {{ github.repository_owner }}
           outputs: dist/snake.svg

       - name: adicionar o arquivo ao repositório
         uses: stefanzweifel/git-auto-commit-action@v5
         with:
          commit_message: "Atualizando a cobrinha"
          file_pattern: "dist/snake.svg"
